version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

      - run: node --version
      - run: npm --version

      - run: npm install
      - run: npm run test-unit
      - run: npm run test-int
      - run: npm run test-proxy
      - run: npm run test-e2e
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                master
    jobs:
      - build
